.TH "Blayer.Data.RepositoryConfiguration" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.RepositoryConfiguration \- Base class for defining repositories  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IEnumerable< \fBIRepository\fP > \fBGetRepositories\fP ()"
.br
.RI "Returns all repositories defined in this "
.in -1c
.SH "Detailed Description"
.PP 
Base class for defining repositories 


.SH "Member Function Documentation"
.PP 
.SS "IEnumerable<\fBIRepository\fP> Blayer\&.Data\&.RepositoryConfiguration\&.GetRepositories ()"

.PP
Returns all repositories defined in this 
.PP
\fBReturns:\fP
.RS 4
All repositories here defined
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
