.TH "Blayer.Data.IModelConfiguration" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.IModelConfiguration \- Allows the repository to modify/create relationships  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConfigure\fP (DbModelBuilder modelBuilder)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows the repository to modify/create relationships 



.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
