.TH "Blayer.Data.Context" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.Context \- Modified version of the DbContext class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits DbContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContext\fP (Dictionary< Type, \fBIRepository\fP > extRepositories)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnModelCreating\fP (DbModelBuilder modelBuilder)"
.br
.RI "Custom model creation to modify data as needed using the \fBIModelConfiguration\fP pattern\&. "
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< Type, \fBIRepository\fP > \fBRepositories\fP"
.br
.RI "Repositories added to the context "
.in -1c
.SH "Detailed Description"
.PP 
Modified version of the DbContext class 


.SH "Member Function Documentation"
.PP 
.SS "override void Blayer\&.Data\&.Context\&.OnModelCreating (DbModelBuilder modelBuilder)\fC [protected]\fP"

.PP
Custom model creation to modify data as needed using the \fBIModelConfiguration\fP pattern\&. 
.PP
\fBParameters:\fP
.RS 4
\fImodelBuilder\fP DbModelBuilder
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Dictionary<Type, \fBIRepository\fP> Blayer\&.Data\&.Context\&.Repositories\fC [static]\fP, \fC [protected]\fP"

.PP
Repositories added to the context 

.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
