.TH "Blayer.Data" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAppContext\fP"
.br
.ti -1c
.RI "class \fBContext\fP"
.br
.RI "Modified version of the DbContext class "
.ti -1c
.RI "class \fBEntityBase\fP"
.br
.RI "Base class for database entities "
.ti -1c
.RI "interface \fBIAdditionalStep\fP"
.br
.RI "Additional steps to be executed every time an entity is added/updated "
.ti -1c
.RI "interface \fBIModelConfiguration\fP"
.br
.RI "Allows the repository to modify/create relationships "
.ti -1c
.RI "interface \fBINotify\fP"
.br
.RI "Notifications be executed every time after an entity is added/updated "
.ti -1c
.RI "interface \fBIRepository\fP"
.br
.RI "Interface for the base repository "
.ti -1c
.RI "interface \fBIValidate\fP"
.br
.RI "Validations executed every time an entity is added/updated "
.ti -1c
.RI "class \fBLoadedEntity\fP"
.br
.RI "Entity loaded to the database "
.ti -1c
.RI "class \fBRepository\fP"
.br
.RI "\fBRepository\fP base class "
.ti -1c
.RI "class \fBRepositoryConfiguration\fP"
.br
.RI "Base class for defining repositories "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
