.TH "Blayer.Data.IValidate" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.IValidate \- Validations executed every time an entity is added/updated  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBValidate\fP (EntityState state, object entityObject, object originalEntity)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Validations executed every time an entity is added/updated 



.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
