.TH "Blayer.Data.IAdditionalStep" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.IAdditionalStep \- Additional steps to be executed every time an entity is added/updated  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBExecute\fP (EntityState state, object entityObject, object originalEntity)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Additional steps to be executed every time an entity is added/updated 



.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
