.TH "Blayer.Data.Utils.BusinessException" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.Utils.BusinessException \- Business exception  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBusinessException\fP (string message, \fBBusinessExceptionType\fP exceptionType=\fBBusinessExceptionType\&.Default\fP)"
.br
.RI "Creates a business exception "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBusinessExceptionType\fP \fBExceptionType\fP\fC [get]\fP"
.br
.RI "Type of exception "
.in -1c
.SH "Detailed Description"
.PP 
Business exception 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Blayer\&.Data\&.Utils\&.BusinessException\&.BusinessException (string message, \fBBusinessExceptionType\fP exceptionType = \fC\fBBusinessExceptionType\&.Default\fP\fP)"

.PP
Creates a business exception 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP Message to be shown to the user
.br
\fIexceptionType\fP Exception type
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBBusinessExceptionType\fP Blayer\&.Data\&.Utils\&.BusinessException\&.ExceptionType\fC [get]\fP"

.PP
Type of exception 

.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
