.TH "Blayer.Data.LoadedEntity" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.LoadedEntity \- Entity loaded to the database  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "DbEntityEntry \fBEntry\fP\fC [get, set]\fP"
.br
.RI "Entry "
.ti -1c
.RI "object \fBOriginalEntity\fP\fC [get, set]\fP"
.br
.RI "Original/unmodified entity "
.ti -1c
.RI "EntityState \fBOriginalState\fP\fC [get, set]\fP"
.br
.RI "Original state "
.in -1c
.SH "Detailed Description"
.PP 
Entity loaded to the database 


.SH "Property Documentation"
.PP 
.SS "DbEntityEntry Blayer\&.Data\&.LoadedEntity\&.Entry\fC [get]\fP, \fC [set]\fP"

.PP
Entry 
.SS "object Blayer\&.Data\&.LoadedEntity\&.OriginalEntity\fC [get]\fP, \fC [set]\fP"

.PP
Original/unmodified entity 
.SS "EntityState Blayer\&.Data\&.LoadedEntity\&.OriginalState\fC [get]\fP, \fC [set]\fP"

.PP
Original state 

.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
