.TH "Blayer.Data.IRepository" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.IRepository \- Interface for the base repository  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBlayer\&.Data\&.IRepository< out out T >\fP, and \fBBlayer\&.Data\&.Repository< T >\fP\&.
.SH "Detailed Description"
.PP 
Interface for the base repository 



.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
