.TH "Blayer.Data.EntityBase" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.EntityBase \- Base class for database entities  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAppContext\fP \fBContext\fP\fC [get, set]\fP"
.br
.RI "Current context "
.ti -1c
.RI "bool \fBWillBeDeleted\fP\fC [get, set]\fP"
.br
.RI "Whether it is marked for removal "
.in -1c
.SH "Detailed Description"
.PP 
Base class for database entities 


.SH "Property Documentation"
.PP 
.SS "\fBAppContext\fP Blayer\&.Data\&.EntityBase\&.Context\fC [get]\fP, \fC [set]\fP"

.PP
Current context 
.SS "bool Blayer\&.Data\&.EntityBase\&.WillBeDeleted\fC [get]\fP, \fC [set]\fP"

.PP
Whether it is marked for removal 

.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
