.TH "Blayer.Data.Repository" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.Repository \- \fBRepository\fP base class  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBlayer\&.Data\&.Repository< T >\fP\&.
.SH "Detailed Description"
.PP 
\fBRepository\fP base class 



.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
