.TH "Blayer.Data.Utils" 3 "Sun Jan 8 2017" "Blayer.Data" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayer.Data.Utils
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBusinessException\fP"
.br
.RI "Business exception "
.ti -1c
.RI "class \fBObjectExtensions\fP"
.br
.RI "Object utilities "
.ti -1c
.RI "class \fBPropertyCopy\fP"
.br
.RI "Copy properties from one instance to another "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBusinessExceptionType\fP { \fBBusinessExceptionType\&.Default\fP = 1 }
.RI "Exception type (business exception) ""
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBlayer\&.Data\&.Utils\&.BusinessExceptionType\fP\fC [strong]\fP"

.PP
Exception type (business exception) 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDefault \fP\fP
Default 
.SH "Author"
.PP 
Generated automatically by Doxygen for Blayer\&.Data from the source code\&.
